---
title: "Software Lifecycle"
subtitle: Designing code
author: albertprofe
date: "06/01/2021"
date-modified: last-modified
date-format: full
description: The software development lifecycle (SDLC) is a process that describes the stages involved in creating and deploying software.
categories: [devops, lifecycle]
toc: true
number-sections: true
highlight-style: pygments
format:
  html

---

# Lifecycle software

And a developer needs such a set skill due to the wide and integral software lifecycle that allows to build apps.

<div class="mermaidContent">
<iframe frameborder="0" style="width:100%;height:600px;" src="https://viewer.diagrams.net/?highlight=0000ff&nav=1&title=LifeCycleSoftwareProject#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D10HyckoCdwJTJ-PNSEZZKogrvhmSIg3Aw%26export%3Ddownload"></iframe>
</div>
</br>

The **software development lifecycle (SDLC)** is a process that describes the stages involved in creating and deploying software. It typically includes the following six steps:

1. **Planning**: This stage involves identifying the goals and objectives of the software, as well as determining the resources and timelines required to develop it.

2. **Design**: In this stage, the software's architecture and user interface are created, and the functional and non-functional requirements are defined.

3. **Test**: This stage involves the implementation of test-driven development (TDD). It starts by writing automated test cases based on the requirements and design of the software. The developer then writes the minimum amount of code needed to pass the test, and repeat this process until all the requirements are met.

4. **Develop**: The actual coding of the software takes place during this stage. This may involve writing code in a specific programming language or using certain development tools.

5. **Maintain**: Once the software is tested and developed, it will be integrated into the primary source code through developer efforts, usually by leveraging training environments to detect further errors or defects.

6. **Deploy**: The final stage is deployment, where the software is made available to users. This may involve installing the software on individual computers or deploying it to a server for multiple users to access.

<!--- navLinks -->
<br><br>
<div class=row>
<br>
<div class='column left previous'>
<br>
[{{< fa solid arrow-left >}} DevOps: immutable infrastructure ](/devops/devops-what-immutable.qmd)
<br>
</div>
<br>
<div class='column center'>
<br>
[{{< fa solid arrow-up >}} top](#top)
<br>
</div>
<br>
<div class='column right next'>
<br>
[How to document: Quarto and Obsidian  {{< fa solid arrow-right >}}](/devops/devops-doc-quarto.qmd)
<br>
</div>
<br>
</div>
