---
title: ""
filters:
   - lightbox
lightbox: auto
format:
  html:
    toc: false
    html-math-method: katex
    highlight-style: atom-one
---

<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto" />

<style>




.animated-text {
  font-size: 204px;
  color: #000;
  font-family; 'Roboto';
  text-align: center;
}
.animated-text-back {
  margin-right: 50px;
  margin-left: 50px;
}
.letter {
  display: inline-block;
  animation: letterAnimation 1s ease-in-out infinite;
  background-color: green; 
  color: white;


}
@keyframes letterAnimation {
  0% { opacity: 0; transform: translateY(-10px); }
  10% { opacity: 1; transform: translateY(0); }
  100% { opacity: 0; transform: translateY(10px); }
}

#spin {
  color:white;
}
#spin:after {
  content:"";
  animation: spin 16s linear infinite;
}
@keyframes spin {
  0% { content:"JAVA";background-color:blue;}
  10% { content:"REACT"; }
  20% { content:"SPRING BOOT"; }
  25% { content: "UML"; }
  30% { content:"BASH"; }
  35% { content:"MINDSET"; }
  40% { content:"SCRUM"; background-color:green;}
  50% { content: "LINUX"; }
  60% { content: "API REST"; }
  70% { content: "DEVOPS"; }
  75% { content: "AWS"; }
  80% { content: "MARKDOWN"; }
  90% { content: "QUARTO";background-color: red; }
}


</style>

::: {.column-screen}

<div class="animated-text">
<p>Code </br><b><span id="spin"></span></b></br>Learn</p>
</div>

:::

<div style="text-align:center;">

[SCRUM](/scrum/scrum-what-concepts.qmd) agile framework |   [Before SCRUM](/scrum/scrum-week10.qmd) management | SCRUM of SCRUM: [Less](/scrum/scrum-week14.qmd#scrum-of-scrum-less) | Team Work, What is it? | [Team Dynamics](/scrum/scrum-week11.qmd), how to manage  | [Mindset](/scrum/scrum-week5.qmd), the key for everything  | [Emotions](/scrum/scrum-week12.qmd) and Thoughts | Managing mind and [time](/scrum/scrum-week7.qmd) | [Beyond SCRUM](/scrum/scrum-week14.qmd)


DDD: Domain-driven design |  [Microservices](https://dotnet.microsoft.com/download/e-book/microservices-architecture/pdf) design system |  [Spring Boot](https://spring.io/) framework | SPA, Single Page App |    Multi-page and server side rendering |    Cloud serveless: [AWS](https://aws.amazon.com/) |  APIs: REST, Websockets, SOAP, GraphQL |  [Kafka](https://kafka.apache.org/intro), event streaming 
 

Scripting: [BASH](/linux/linux-what-bash.qmd), (short for “Bourne again shell”) is a Unix shell |  Structured and Procedural: C |   OOP (Object-Oriented Programming): [Java SE](https://java-programming.mooc.fi/) |  COP (Components-Oriented Programming): [React JS](https://reactjs.org/) and [React TS](https://www.typescriptlang.org/docs/handbook/react.html)  
 
 

[Git](/devops/devops-vc-git.qmd), a version control system |  [Git](https://git-scm.com/) is used for source code management |   [GitHub](https://github.com/) git on cloud |  GitLab / Subversion |   [Idea](/devops/devops-vc-ideagithub.qmd) and GitHub 2023 |  [Git and GitHub 2023 CLI](/devops/devops-vc-gitgh.qmd) |  [CLI gH](https://cli.github.com/), to your terminal |   IDE: [Visual Code](/devops/devops-ide-visualcode.qmd) / IntellJ Idea 
 
  

[about this site](about/about-this-site.qmd), for documentation example. |  [JUnit for Spring Boot](https://junit.org/junit5/) |  [Jest for JS React](https://jestjs.io/) |  Deploy on Heroku, Netlify, AWS Amplify |  [Jenkins](https://www.jenkins.io/), [Docker](https://www.docker.com/) and [k8s](https://kubernetes.io/) 
 



[Artificial Intelligence (AI):](https://www.investopedia.com/terms/a/artificial-intelligence-ai.asp) What It Is and How It Is Used |  Machine Learning |  Natural language & prompts |  [DALL-E](https://www.investopedia.com/openai-rolls-out-upgraded-ai-image-generation-tool-with-dall-e-3-7972607) text-to-image tool |  [ChatGPT](https://openai.com/blog/chatgpt) |  Artificial General Intelligence (AGI) |  AI is categorized into four types  


<div>



