---
title: "Week 3: Communication and value"
subtitle: SCRUM Week 3
author: albertprofe
date: "06/01/2021"
date-modified: last-modified
date-format: full
description: description
categories: [scrum, scrum-wewek3, communication]
toc: true
number-sections: true
format:
  html
---

# Communication: deliver value


Effective communication hinges on delivering value to your audience. Understand their needs, tailoring messages to resonate with their interests and knowledge. Keep communication clear, concise, and relevant, avoiding unnecessary complexity. Actively listen, displaying genuine interest in others' perspectives, and respond thoughtfully. Provide practical solutions or insights that address their challenges, emphasizing the benefits. Demonstrate empathy, acknowledging emotions and showing that you care.

Positive reinforcement fosters collaboration, appreciating contributions and maintaining a constructive atmosphere. Clearly communicate expectations to avoid misunderstandings, promoting efficiency. Utilize visuals and examples when applicable to enhance understanding. Encourage a feedback loop, learning from input and adapting your communication style accordingly. Follow up after interactions to ensure expectations are met, displaying ongoing commitment. By consistently applying these principles, you establish meaningful connections and contribute value to every interaction.

# Writing & Speaking

## The mom test

The Mom Test: How to talk to customers & learn if your business is a good idea when everyone is lying to you


- They say you shouldn't ask your mom whether your business is a good idea, because she loves you and will lie to you. This is technically true, but it misses the point. 
- You shouldn't ask anyone if your business is a good idea. 
- It's a bad question and everyone will lie to you at least a little. 
- As a matter of fact, it's not their responsibility to tell you the truth: It's your responsibility to find it and it's worth doing right.

## Words

Using the right words and a common vocabulary is crucial for effective communication.

It ensures clarity, reduces misunderstandings, and promotes a shared understanding. Precision in language choice minimizes confusion and facilitates seamless dialogue in various contexts—be it professional interactions or personal relationships.

A common vocabulary establishes a baseline for meaningful communication, fostering connection and collaboration. 

## Writing

In effective writing, clarity is paramount. Clearly articulate your message, tailoring it to your audience's needs.

Use concise language to convey ideas efficiently, avoiding unnecessary complexity. Employ a feedback loop, welcome input, and adapt your writing style accordingly. Illustrate points with relevant examples for enhanced understanding. Positive reinforcement in your writing can engage readers, and thoughtful follow-up ensures the communication loop is complete. By concentrating on these principles—clarity, conciseness, adaptability, engagement, and follow-up—you create written communication that is not only informative but also impactful and conducive to meaningful interactions.

## Speaking

In effective speaking, prioritize clarity and conciseness to convey your message with precision. Tailor your spoken words to your audience, considering their needs and understanding.

Actively listen, responding thoughtfully to promote engagement. Positive reinforcement in speech fosters a collaborative atmosphere. Adapt your speaking style based on feedback, ensuring effective communication. Utilize relevant examples and visuals to enhance understanding. Follow up verbally to reinforce key points and maintain connections. By concentrating on clarity, audience adaptation, engagement, feedback, and reinforcement, your spoken communication becomes not just informative but also impactful, fostering meaningful interactions and connections with your audience.

# Parecto Principle

The Pareto principle states that for many outcomes, roughly 80% of consequences come from 20% of causes (the "vital few").

Other names for this principle are the 80/20 rule, the law of the vital few, or the principle of factor sparsity.

- Language : The most frequently used 20% of the words account for 80% of the word occurrences.
- Land Owners : In 1896, Vilfredo Pareto showed that around 80% of the land in Italy was owned by just 20% of population.
- World's Income : The richest 20% of the humans have 80% of worlds income.
- Health Care : In the US, 20% of the patients use80% of the health care resources.
- Errors : In 2002, Microsoft reported that 80% of the errors and crashes in windows and office are caused by 20% of the bugs involved.
- Business : 20% of the customers are responsible for the 80% of the profit earned and 20% of the complaints received come from 80% of the customers.
- Resources : In home or office, 20 % of the carpet receives 80% of the wear.
- Clothing and Life Style : People wear around 20% of their clothes 80% of the times.
- Fund Raising: The Pareto principle applies to raising funds: 20% of the donors contribute 80% of the total .

https://en.wikipedia.org/wiki/Pareto_principle
https://sites.google.com/view/gestioprojectes/llegir/setmana3/pareto


# Multitasking

Doing more than one task at a time, especially more than one complex task, takes a toll on productivity.

Although that shouldn’t surprise many people, the extent of the problem might come as a shock. Psychologists who study what happens to cognition (mental processes) when people multitask found that our brains were not designed for it.

Stanford’s professor of communication Clifford Nass, on an NPR broadcast, had clearly summarized the findings:

“The research is almost unanimous, which is very rare in social science, and it says that people who chronically multitask show an enormous range of deficits. They’re basically terrible at all sorts of cognitive tasks, including multitasking… People who multitask all the time can’t filter out irrelevancy. They can’t manage a working memory.
They’re chronically distracted [but] they actually think they’re more productive… [They say,] “When I really have to concentrate, I turn off everything and I am laser-focused.” And unfortunately, they’ve developed habits of mind that make it impossible for them to be laser-focused. They’re suckers for irrelevancy. They just can’t keep on task.”


It translates into a:

- Struggle to prioritize: The never-ending change in tasks makes it difficult for us to judge which ones are important, which are urgent and which are just time-filling distractions;
- More error: The overall quality of our work plummets, which results in more manual errors or poor decision-making;
- Productivity loss: Research found that even brief mental blocks created by shifting between tasks can cost as much as 40% of someones productive time.
- At the end multitasking makes us look and feel busy, but actually harm the quality and quantity of our initiatives.


And there are more negative side-effects: because of our brains’ plasticity, when we consistently engage in multi-tasking we reshape our brains for the worse, and we become habituated to this counterproductive way of working. 

https://sites.google.com/view/gestioprojectes/llegir/setmana3/multitasking


# Halo effect

The halo effect is a cognitive bias that occurs when an initial positive judgment about a person unconsciously colors the perception of the individual as a whole.

When forming a first impression, observing an initial attractive feature—perhaps beauty or strength—can make the person appealing, making it difficult to revise that impression based on new or opposing information. For example, an attractive individual may also be perceived as interesting, ambitious, or funny, whether or not that assessment is warranted.


https://www.psychologytoday.com/intl/basics/halo-effect
https://www.strategyzer.com/library/dont-fall-in-love-with-your-first-idea

# References

- [Week 3: Communication and value](https://sites.google.com/view/gestioprojectes/llegir/setmana3){.external}


<!--- navLinks -->
<br><br>
<div class=row>
<br>
<div class='column left previous'>
<br>
[{{< fa solid arrow-left >}} Week 2: User stories, tasks and habits](/scrum/scrum-week2.qmd)
<br>
</div>
<br>
<div class='column center'>
<br>
[{{< fa solid arrow-up >}} top](#top)
<br>
</div>
<br>
<div class='column right next'>
<br>
[Week 4: ScrumMaster, how it works  {{< fa solid arrow-right >}}](/scrum/scrum-week4.qmd)
<br>
</div>
<br>
</div>
