---
title: "Week 4: ScrumMaster, how it works"
subtitle: SCRUM Week 4
author: albertprofe
date: "06/01/2021"
date-modified: last-modified
date-format: full
description: description
categories: [scrum, scrum-week4, scrummaster]
toc: true
number-sections: true
format:
  html
---

# ScrumMaster, how it works

- [Week 4: ScrumMaster, how it works](https://sites.google.com/view/gestioprojectes/llegir/setmana4){.external}

Organizations across all industries globally are hiring Scrum masters because they are experts in handling challenging tasks.
They address complex issues during the lifecycle of a project, ranging from motivating, leading, and training the team to respect the timelines; coordinating with the stakeholders, product owners, managers, and developers; and onboarding project teams. 
A Scrum master acts as a bridge between a product/business owner to facilitate accountability at every level. 
They ensure that everyone is on the same page and help the team meet deadlines and deliverables within budget.


Organizations across all industries globally are hiring Scrum masters because they are experts in handling challenging tasks.
They address complex issues during the lifecycle of a project, ranging from motivating, leading, and training the team to respect the timelines; coordinating with the stakeholders, product owners, managers, and developers; and onboarding project teams. 
A Scrum master acts as a bridge between a product/business owner to facilitate accountability at every level. 
They ensure that everyone is on the same page and help the team meet deadlines and deliverables within budget.

Changes as a Scrum Master:

Product vision
More ownership
Better quality
Less centralised management
Better planning
Better product



<!--- navLinks -->
<br><br>
<div class=row>
<br>
<div class='column left previous'>
<br>
[{{< fa solid arrow-left >}} Week 3: Communication and value](/scrum/scrum-week3.qmd)
<br>
</div>
<br>
<div class='column center'>
<br>
[{{< fa solid arrow-up >}} top](#top)
<br>
</div>
<br>
<div class='column right next'>
<br>
[Week 5: Mindset, the key to everythng  {{< fa solid arrow-right >}}](/scrum/scrum-week5.qmd)
<br>
</div>
<br>
</div>
